// Generated by :data-ingestion:codegenSpecies — do not edit.
// Source of truth: engine/src/main/resources/pokedex/species/<slug>.json (diary 064).
// Re-run `./gradlew :data-ingestion:codegenSpecies` to regenerate after re-ingestion.
package com.pokemon.battle.data

import com.pokemon.battle.model.Species
import com.pokemon.battle.model.Type

/**
 * Generated species catalog. Symbol-keyed counterpart to
 * [Pokedex.loadJsonFromClasspath]; both produce the same domain values.
 * Pick whichever consumption shape suits the call site (see diary 064).
 */
@Suppress("LargeClass", "ObjectPropertyNaming") // Generated; one val per species.
object PokedexCatalog {
    val ALAKAZAM: Species =
        Species(
            name = "Alakazam",
            types = listOf(Type.PSYCHIC),
            baseHp = 55,
            baseAttack = 50,
            baseDefense = 45,
            baseSpecialAttack = 135,
            baseSpecialDefense = 95,
            baseSpeed = 120,
        )

    val ALOMOMOLA: Species =
        Species(
            name = "Alomomola",
            types = listOf(Type.WATER),
            baseHp = 165,
            baseAttack = 75,
            baseDefense = 80,
            baseSpecialAttack = 40,
            baseSpecialDefense = 45,
            baseSpeed = 65,
        )

    val AMOONGUSS: Species =
        Species(
            name = "Amoonguss",
            types = listOf(Type.GRASS, Type.POISON),
            baseHp = 114,
            baseAttack = 85,
            baseDefense = 70,
            baseSpecialAttack = 85,
            baseSpecialDefense = 80,
            baseSpeed = 30,
        )

    val ARCANINE_HISUI: Species =
        Species(
            name = "Arcanine Hisui",
            types = listOf(Type.FIRE, Type.ROCK),
            baseHp = 95,
            baseAttack = 115,
            baseDefense = 80,
            baseSpecialAttack = 95,
            baseSpecialDefense = 80,
            baseSpeed = 90,
        )

    val ARCHALUDON: Species =
        Species(
            name = "Archaludon",
            types = listOf(Type.STEEL, Type.DRAGON),
            baseHp = 90,
            baseAttack = 105,
            baseDefense = 130,
            baseSpecialAttack = 125,
            baseSpecialDefense = 65,
            baseSpeed = 85,
        )

    val BLACEPHALON: Species =
        Species(
            name = "Blacephalon",
            types = listOf(Type.FIRE, Type.GHOST),
            baseHp = 53,
            baseAttack = 127,
            baseDefense = 53,
            baseSpecialAttack = 151,
            baseSpecialDefense = 79,
            baseSpeed = 107,
        )

    val BLASTOISE: Species =
        Species(
            name = "Blastoise",
            types = listOf(Type.WATER),
            baseHp = 79,
            baseAttack = 83,
            baseDefense = 100,
            baseSpecialAttack = 85,
            baseSpecialDefense = 105,
            baseSpeed = 78,
        )

    val BLAZIKEN: Species =
        Species(
            name = "Blaziken",
            types = listOf(Type.FIRE, Type.FIGHTING),
            baseHp = 80,
            baseAttack = 120,
            baseDefense = 70,
            baseSpecialAttack = 110,
            baseSpecialDefense = 70,
            baseSpeed = 80,
        )

    val BLISSEY: Species =
        Species(
            name = "Blissey",
            types = listOf(Type.NORMAL),
            baseHp = 255,
            baseAttack = 10,
            baseDefense = 10,
            baseSpecialAttack = 75,
            baseSpecialDefense = 135,
            baseSpeed = 55,
        )

    val BRELOOM: Species =
        Species(
            name = "Breloom",
            types = listOf(Type.GRASS, Type.FIGHTING),
            baseHp = 60,
            baseAttack = 130,
            baseDefense = 80,
            baseSpecialAttack = 60,
            baseSpecialDefense = 60,
            baseSpeed = 70,
        )

    val CERULEDGE: Species =
        Species(
            name = "Ceruledge",
            types = listOf(Type.FIRE, Type.GHOST),
            baseHp = 75,
            baseAttack = 125,
            baseDefense = 80,
            baseSpecialAttack = 60,
            baseSpecialDefense = 100,
            baseSpeed = 85,
        )

    val CHARIZARD: Species =
        Species(
            name = "Charizard",
            types = listOf(Type.FIRE, Type.FLYING),
            baseHp = 78,
            baseAttack = 84,
            baseDefense = 78,
            baseSpecialAttack = 109,
            baseSpecialDefense = 85,
            baseSpeed = 100,
        )

    val CHI_YU: Species =
        Species(
            name = "Chi Yu",
            types = listOf(Type.DARK, Type.FIRE),
            baseHp = 55,
            baseAttack = 80,
            baseDefense = 80,
            baseSpecialAttack = 135,
            baseSpecialDefense = 120,
            baseSpeed = 100,
        )

    val CHIEN_PAO: Species =
        Species(
            name = "Chien Pao",
            types = listOf(Type.DARK, Type.ICE),
            baseHp = 80,
            baseAttack = 120,
            baseDefense = 80,
            baseSpecialAttack = 90,
            baseSpecialDefense = 65,
            baseSpeed = 135,
        )

    val CINDERACE: Species =
        Species(
            name = "Cinderace",
            types = listOf(Type.FIRE),
            baseHp = 80,
            baseAttack = 116,
            baseDefense = 75,
            baseSpecialAttack = 65,
            baseSpecialDefense = 75,
            baseSpeed = 119,
        )

    val CLEFABLE: Species =
        Species(
            name = "Clefable",
            types = listOf(Type.FAIRY),
            baseHp = 95,
            baseAttack = 70,
            baseDefense = 73,
            baseSpecialAttack = 95,
            baseSpecialDefense = 90,
            baseSpeed = 60,
        )

    val CONKELDURR: Species =
        Species(
            name = "Conkeldurr",
            types = listOf(Type.FIGHTING),
            baseHp = 105,
            baseAttack = 140,
            baseDefense = 95,
            baseSpecialAttack = 55,
            baseSpecialDefense = 65,
            baseSpeed = 45,
        )

    val CORVIKNIGHT: Species =
        Species(
            name = "Corviknight",
            types = listOf(Type.FLYING, Type.STEEL),
            baseHp = 98,
            baseAttack = 87,
            baseDefense = 105,
            baseSpecialAttack = 53,
            baseSpecialDefense = 85,
            baseSpeed = 67,
        )

    val CRAWDAUNT: Species =
        Species(
            name = "Crawdaunt",
            types = listOf(Type.WATER, Type.DARK),
            baseHp = 63,
            baseAttack = 120,
            baseDefense = 85,
            baseSpecialAttack = 90,
            baseSpecialDefense = 55,
            baseSpeed = 55,
        )

    val DARKRAI: Species =
        Species(
            name = "Darkrai",
            types = listOf(Type.DARK),
            baseHp = 70,
            baseAttack = 90,
            baseDefense = 90,
            baseSpecialAttack = 135,
            baseSpecialDefense = 90,
            baseSpeed = 125,
        )

    val DONDOZO: Species =
        Species(
            name = "Dondozo",
            types = listOf(Type.WATER),
            baseHp = 150,
            baseAttack = 100,
            baseDefense = 115,
            baseSpecialAttack = 65,
            baseSpecialDefense = 65,
            baseSpeed = 35,
        )

    val DRAGAPULT: Species =
        Species(
            name = "Dragapult",
            types = listOf(Type.DRAGON, Type.GHOST),
            baseHp = 88,
            baseAttack = 120,
            baseDefense = 75,
            baseSpecialAttack = 100,
            baseSpecialDefense = 75,
            baseSpeed = 142,
        )

    val DRAGONITE: Species =
        Species(
            name = "Dragonite",
            types = listOf(Type.DRAGON, Type.FLYING),
            baseHp = 91,
            baseAttack = 134,
            baseDefense = 95,
            baseSpecialAttack = 100,
            baseSpecialDefense = 100,
            baseSpeed = 80,
        )

    val EXCADRILL: Species =
        Species(
            name = "Excadrill",
            types = listOf(Type.GROUND, Type.STEEL),
            baseHp = 110,
            baseAttack = 135,
            baseDefense = 60,
            baseSpecialAttack = 50,
            baseSpecialDefense = 65,
            baseSpeed = 88,
        )

    val FARIGIRAF: Species =
        Species(
            name = "Farigiraf",
            types = listOf(Type.NORMAL, Type.PSYCHIC),
            baseHp = 120,
            baseAttack = 90,
            baseDefense = 70,
            baseSpecialAttack = 110,
            baseSpecialDefense = 70,
            baseSpeed = 60,
        )

    val FERROTHORN: Species =
        Species(
            name = "Ferrothorn",
            types = listOf(Type.GRASS, Type.STEEL),
            baseHp = 74,
            baseAttack = 94,
            baseDefense = 131,
            baseSpecialAttack = 54,
            baseSpecialDefense = 116,
            baseSpeed = 20,
        )

    val FLUTTER_MANE: Species =
        Species(
            name = "Flutter Mane",
            types = listOf(Type.GHOST, Type.FAIRY),
            baseHp = 55,
            baseAttack = 55,
            baseDefense = 55,
            baseSpecialAttack = 135,
            baseSpecialDefense = 135,
            baseSpeed = 135,
        )

    val FORRETRESS: Species =
        Species(
            name = "Forretress",
            types = listOf(Type.BUG, Type.STEEL),
            baseHp = 75,
            baseAttack = 90,
            baseDefense = 140,
            baseSpecialAttack = 60,
            baseSpecialDefense = 60,
            baseSpeed = 40,
        )

    val GARCHOMP: Species =
        Species(
            name = "Garchomp",
            types = listOf(Type.DRAGON, Type.GROUND),
            baseHp = 108,
            baseAttack = 130,
            baseDefense = 95,
            baseSpecialAttack = 80,
            baseSpecialDefense = 85,
            baseSpeed = 102,
        )

    val GARGANACL: Species =
        Species(
            name = "Garganacl",
            types = listOf(Type.ROCK),
            baseHp = 100,
            baseAttack = 100,
            baseDefense = 130,
            baseSpecialAttack = 45,
            baseSpecialDefense = 90,
            baseSpeed = 35,
        )

    val GENGAR: Species =
        Species(
            name = "Gengar",
            types = listOf(Type.GHOST, Type.POISON),
            baseHp = 60,
            baseAttack = 65,
            baseDefense = 60,
            baseSpecialAttack = 130,
            baseSpecialDefense = 75,
            baseSpeed = 110,
        )

    val GHOLDENGO: Species =
        Species(
            name = "Gholdengo",
            types = listOf(Type.STEEL, Type.GHOST),
            baseHp = 87,
            baseAttack = 60,
            baseDefense = 95,
            baseSpecialAttack = 133,
            baseSpecialDefense = 91,
            baseSpeed = 84,
        )

    val GLIMMORA: Species =
        Species(
            name = "Glimmora",
            types = listOf(Type.ROCK, Type.POISON),
            baseHp = 83,
            baseAttack = 55,
            baseDefense = 90,
            baseSpecialAttack = 130,
            baseSpecialDefense = 81,
            baseSpeed = 86,
        )

    val GLISCOR: Species =
        Species(
            name = "Gliscor",
            types = listOf(Type.GROUND, Type.FLYING),
            baseHp = 75,
            baseAttack = 95,
            baseDefense = 125,
            baseSpecialAttack = 45,
            baseSpecialDefense = 75,
            baseSpeed = 95,
        )

    val GREAT_TUSK: Species =
        Species(
            name = "Great Tusk",
            types = listOf(Type.GROUND, Type.FIGHTING),
            baseHp = 115,
            baseAttack = 131,
            baseDefense = 131,
            baseSpecialAttack = 53,
            baseSpecialDefense = 53,
            baseSpeed = 87,
        )

    val HATTERENE: Species =
        Species(
            name = "Hatterene",
            types = listOf(Type.PSYCHIC, Type.FAIRY),
            baseHp = 57,
            baseAttack = 90,
            baseDefense = 95,
            baseSpecialAttack = 136,
            baseSpecialDefense = 103,
            baseSpeed = 29,
        )

    val HEATRAN: Species =
        Species(
            name = "Heatran",
            types = listOf(Type.FIRE, Type.STEEL),
            baseHp = 91,
            baseAttack = 90,
            baseDefense = 106,
            baseSpecialAttack = 130,
            baseSpecialDefense = 106,
            baseSpeed = 77,
        )

    val INCINEROAR: Species =
        Species(
            name = "Incineroar",
            types = listOf(Type.FIRE, Type.DARK),
            baseHp = 95,
            baseAttack = 115,
            baseDefense = 90,
            baseSpecialAttack = 80,
            baseSpecialDefense = 90,
            baseSpeed = 60,
        )

    val INDEEDEE_FEMALE: Species =
        Species(
            name = "Indeedee Female",
            types = listOf(Type.PSYCHIC, Type.NORMAL),
            baseHp = 70,
            baseAttack = 55,
            baseDefense = 65,
            baseSpecialAttack = 95,
            baseSpecialDefense = 105,
            baseSpeed = 85,
        )

    val IRON_CROWN: Species =
        Species(
            name = "Iron Crown",
            types = listOf(Type.STEEL, Type.PSYCHIC),
            baseHp = 90,
            baseAttack = 72,
            baseDefense = 100,
            baseSpecialAttack = 122,
            baseSpecialDefense = 108,
            baseSpeed = 98,
        )

    val IRON_MOTH: Species =
        Species(
            name = "Iron Moth",
            types = listOf(Type.FIRE, Type.POISON),
            baseHp = 80,
            baseAttack = 70,
            baseDefense = 60,
            baseSpecialAttack = 140,
            baseSpecialDefense = 110,
            baseSpeed = 110,
        )

    val IRON_TREADS: Species =
        Species(
            name = "Iron Treads",
            types = listOf(Type.GROUND, Type.STEEL),
            baseHp = 90,
            baseAttack = 112,
            baseDefense = 120,
            baseSpecialAttack = 72,
            baseSpecialDefense = 70,
            baseSpeed = 106,
        )

    val IRON_VALIANT: Species =
        Species(
            name = "Iron Valiant",
            types = listOf(Type.FAIRY, Type.FIGHTING),
            baseHp = 74,
            baseAttack = 130,
            baseDefense = 90,
            baseSpecialAttack = 120,
            baseSpecialDefense = 60,
            baseSpeed = 116,
        )

    val JELLICENT_MALE: Species =
        Species(
            name = "Jellicent Male",
            types = listOf(Type.WATER, Type.GHOST),
            baseHp = 100,
            baseAttack = 60,
            baseDefense = 70,
            baseSpecialAttack = 85,
            baseSpecialDefense = 105,
            baseSpeed = 60,
        )

    val JIRACHI: Species =
        Species(
            name = "Jirachi",
            types = listOf(Type.STEEL, Type.PSYCHIC),
            baseHp = 100,
            baseAttack = 100,
            baseDefense = 100,
            baseSpecialAttack = 100,
            baseSpecialDefense = 100,
            baseSpeed = 100,
        )

    val KARTANA: Species =
        Species(
            name = "Kartana",
            types = listOf(Type.GRASS, Type.STEEL),
            baseHp = 59,
            baseAttack = 181,
            baseDefense = 131,
            baseSpecialAttack = 59,
            baseSpecialDefense = 31,
            baseSpeed = 109,
        )

    val KELDEO_ORDINARY: Species =
        Species(
            name = "Keldeo Ordinary",
            types = listOf(Type.WATER, Type.FIGHTING),
            baseHp = 91,
            baseAttack = 72,
            baseDefense = 90,
            baseSpecialAttack = 129,
            baseSpecialDefense = 90,
            baseSpeed = 108,
        )

    val KINGAMBIT: Species =
        Species(
            name = "Kingambit",
            types = listOf(Type.DARK, Type.STEEL),
            baseHp = 100,
            baseAttack = 135,
            baseDefense = 120,
            baseSpecialAttack = 60,
            baseSpecialDefense = 85,
            baseSpeed = 50,
        )

    val KYUREM: Species =
        Species(
            name = "Kyurem",
            types = listOf(Type.DRAGON, Type.ICE),
            baseHp = 125,
            baseAttack = 130,
            baseDefense = 90,
            baseSpecialAttack = 130,
            baseSpecialDefense = 90,
            baseSpeed = 95,
        )

    val KYUREM_BLACK: Species =
        Species(
            name = "Kyurem Black",
            types = listOf(Type.DRAGON, Type.ICE),
            baseHp = 125,
            baseAttack = 170,
            baseDefense = 100,
            baseSpecialAttack = 120,
            baseSpecialDefense = 90,
            baseSpeed = 95,
        )

    val LANDORUS_INCARNATE: Species =
        Species(
            name = "Landorus Incarnate",
            types = listOf(Type.GROUND, Type.FLYING),
            baseHp = 89,
            baseAttack = 125,
            baseDefense = 90,
            baseSpecialAttack = 115,
            baseSpecialDefense = 80,
            baseSpeed = 101,
        )

    val LANDORUS_THERIAN: Species =
        Species(
            name = "Landorus Therian",
            types = listOf(Type.GROUND, Type.FLYING),
            baseHp = 89,
            baseAttack = 145,
            baseDefense = 90,
            baseSpecialAttack = 105,
            baseSpecialDefense = 80,
            baseSpeed = 91,
        )

    val LATIOS: Species =
        Species(
            name = "Latios",
            types = listOf(Type.DRAGON, Type.PSYCHIC),
            baseHp = 80,
            baseAttack = 90,
            baseDefense = 80,
            baseSpecialAttack = 130,
            baseSpecialDefense = 110,
            baseSpeed = 110,
        )

    val MAGNEZONE: Species =
        Species(
            name = "Magnezone",
            types = listOf(Type.ELECTRIC, Type.STEEL),
            baseHp = 70,
            baseAttack = 70,
            baseDefense = 115,
            baseSpecialAttack = 130,
            baseSpecialDefense = 90,
            baseSpeed = 60,
        )

    val MELMETAL: Species =
        Species(
            name = "Melmetal",
            types = listOf(Type.STEEL),
            baseHp = 135,
            baseAttack = 143,
            baseDefense = 143,
            baseSpecialAttack = 80,
            baseSpecialDefense = 65,
            baseSpeed = 34,
        )

    val MEW: Species =
        Species(
            name = "Mew",
            types = listOf(Type.PSYCHIC),
            baseHp = 100,
            baseAttack = 100,
            baseDefense = 100,
            baseSpecialAttack = 100,
            baseSpecialDefense = 100,
            baseSpeed = 100,
        )

    val NINETALES: Species =
        Species(
            name = "Ninetales",
            types = listOf(Type.FIRE),
            baseHp = 73,
            baseAttack = 76,
            baseDefense = 75,
            baseSpecialAttack = 81,
            baseSpecialDefense = 100,
            baseSpeed = 100,
        )

    val NINETALES_ALOLA: Species =
        Species(
            name = "Ninetales Alola",
            types = listOf(Type.ICE, Type.FAIRY),
            baseHp = 73,
            baseAttack = 67,
            baseDefense = 75,
            baseSpecialAttack = 81,
            baseSpecialDefense = 100,
            baseSpeed = 109,
        )

    val OGERPON_HEARTHFLAME_MASK: Species =
        Species(
            name = "Ogerpon Hearthflame Mask",
            types = listOf(Type.GRASS, Type.FIRE),
            baseHp = 80,
            baseAttack = 120,
            baseDefense = 84,
            baseSpecialAttack = 60,
            baseSpecialDefense = 96,
            baseSpeed = 110,
        )

    val OGERPON_WELLSPRING_MASK: Species =
        Species(
            name = "Ogerpon Wellspring Mask",
            types = listOf(Type.GRASS, Type.WATER),
            baseHp = 80,
            baseAttack = 120,
            baseDefense = 84,
            baseSpecialAttack = 60,
            baseSpecialDefense = 96,
            baseSpeed = 110,
        )

    val PECHARUNT: Species =
        Species(
            name = "Pecharunt",
            types = listOf(Type.POISON, Type.GHOST),
            baseHp = 88,
            baseAttack = 88,
            baseDefense = 160,
            baseSpecialAttack = 88,
            baseSpecialDefense = 88,
            baseSpeed = 88,
        )

    val PELIPPER: Species =
        Species(
            name = "Pelipper",
            types = listOf(Type.WATER, Type.FLYING),
            baseHp = 60,
            baseAttack = 50,
            baseDefense = 100,
            baseSpecialAttack = 95,
            baseSpecialDefense = 70,
            baseSpeed = 65,
        )

    val PIKACHU: Species =
        Species(
            name = "Pikachu",
            types = listOf(Type.ELECTRIC),
            baseHp = 35,
            baseAttack = 55,
            baseDefense = 40,
            baseSpecialAttack = 50,
            baseSpecialDefense = 50,
            baseSpeed = 90,
        )

    val POLITOED: Species =
        Species(
            name = "Politoed",
            types = listOf(Type.WATER),
            baseHp = 90,
            baseAttack = 75,
            baseDefense = 75,
            baseSpecialAttack = 90,
            baseSpecialDefense = 100,
            baseSpeed = 70,
        )

    val RAGING_BOLT: Species =
        Species(
            name = "Raging Bolt",
            types = listOf(Type.ELECTRIC, Type.DRAGON),
            baseHp = 125,
            baseAttack = 73,
            baseDefense = 91,
            baseSpecialAttack = 137,
            baseSpecialDefense = 89,
            baseSpeed = 75,
        )

    val REGIDRAGO: Species =
        Species(
            name = "Regidrago",
            types = listOf(Type.DRAGON),
            baseHp = 200,
            baseAttack = 100,
            baseDefense = 50,
            baseSpecialAttack = 100,
            baseSpecialDefense = 50,
            baseSpeed = 80,
        )

    val REUNICLUS: Species =
        Species(
            name = "Reuniclus",
            types = listOf(Type.PSYCHIC),
            baseHp = 110,
            baseAttack = 65,
            baseDefense = 75,
            baseSpecialAttack = 125,
            baseSpecialDefense = 85,
            baseSpeed = 30,
        )

    val RILLABOOM: Species =
        Species(
            name = "Rillaboom",
            types = listOf(Type.GRASS),
            baseHp = 100,
            baseAttack = 125,
            baseDefense = 90,
            baseSpecialAttack = 60,
            baseSpecialDefense = 70,
            baseSpeed = 85,
        )

    val ROTOM_WASH: Species =
        Species(
            name = "Rotom Wash",
            types = listOf(Type.ELECTRIC, Type.WATER),
            baseHp = 50,
            baseAttack = 65,
            baseDefense = 107,
            baseSpecialAttack = 105,
            baseSpecialDefense = 107,
            baseSpeed = 86,
        )

    val SAMUROTT_HISUI: Species =
        Species(
            name = "Samurott Hisui",
            types = listOf(Type.WATER, Type.DARK),
            baseHp = 90,
            baseAttack = 108,
            baseDefense = 80,
            baseSpecialAttack = 100,
            baseSpecialDefense = 65,
            baseSpeed = 85,
        )

    val SCIZOR: Species =
        Species(
            name = "Scizor",
            types = listOf(Type.BUG, Type.STEEL),
            baseHp = 70,
            baseAttack = 130,
            baseDefense = 100,
            baseSpecialAttack = 55,
            baseSpecialDefense = 80,
            baseSpeed = 65,
        )

    val SKARMORY: Species =
        Species(
            name = "Skarmory",
            types = listOf(Type.STEEL, Type.FLYING),
            baseHp = 65,
            baseAttack = 80,
            baseDefense = 140,
            baseSpecialAttack = 40,
            baseSpecialDefense = 70,
            baseSpeed = 70,
        )

    val SLOWBRO: Species =
        Species(
            name = "Slowbro",
            types = listOf(Type.WATER, Type.PSYCHIC),
            baseHp = 95,
            baseAttack = 75,
            baseDefense = 110,
            baseSpecialAttack = 100,
            baseSpecialDefense = 80,
            baseSpeed = 30,
        )

    val SLOWKING_GALAR: Species =
        Species(
            name = "Slowking Galar",
            types = listOf(Type.POISON, Type.PSYCHIC),
            baseHp = 95,
            baseAttack = 65,
            baseDefense = 80,
            baseSpecialAttack = 110,
            baseSpecialDefense = 110,
            baseSpeed = 30,
        )

    val STARMIE: Species =
        Species(
            name = "Starmie",
            types = listOf(Type.WATER, Type.PSYCHIC),
            baseHp = 60,
            baseAttack = 75,
            baseDefense = 85,
            baseSpecialAttack = 100,
            baseSpecialDefense = 85,
            baseSpeed = 115,
        )

    val TAPU_FINI: Species =
        Species(
            name = "Tapu Fini",
            types = listOf(Type.WATER, Type.FAIRY),
            baseHp = 70,
            baseAttack = 75,
            baseDefense = 115,
            baseSpecialAttack = 95,
            baseSpecialDefense = 130,
            baseSpeed = 85,
        )

    val TAPU_KOKO: Species =
        Species(
            name = "Tapu Koko",
            types = listOf(Type.ELECTRIC, Type.FAIRY),
            baseHp = 70,
            baseAttack = 115,
            baseDefense = 85,
            baseSpecialAttack = 95,
            baseSpecialDefense = 75,
            baseSpeed = 130,
        )

    val TAPU_LELE: Species =
        Species(
            name = "Tapu Lele",
            types = listOf(Type.PSYCHIC, Type.FAIRY),
            baseHp = 70,
            baseAttack = 85,
            baseDefense = 75,
            baseSpecialAttack = 130,
            baseSpecialDefense = 115,
            baseSpeed = 95,
        )

    val TATSUGIRI_CURLY: Species =
        Species(
            name = "Tatsugiri Curly",
            types = listOf(Type.DRAGON, Type.WATER),
            baseHp = 68,
            baseAttack = 50,
            baseDefense = 60,
            baseSpecialAttack = 120,
            baseSpecialDefense = 95,
            baseSpeed = 82,
        )

    val TENTACRUEL: Species =
        Species(
            name = "Tentacruel",
            types = listOf(Type.WATER, Type.POISON),
            baseHp = 80,
            baseAttack = 70,
            baseDefense = 65,
            baseSpecialAttack = 80,
            baseSpecialDefense = 120,
            baseSpeed = 100,
        )

    val THUNDURUS_THERIAN: Species =
        Species(
            name = "Thundurus Therian",
            types = listOf(Type.ELECTRIC, Type.FLYING),
            baseHp = 79,
            baseAttack = 105,
            baseDefense = 70,
            baseSpecialAttack = 145,
            baseSpecialDefense = 80,
            baseSpeed = 101,
        )

    val TING_LU: Species =
        Species(
            name = "Ting Lu",
            types = listOf(Type.DARK, Type.GROUND),
            baseHp = 155,
            baseAttack = 110,
            baseDefense = 125,
            baseSpecialAttack = 55,
            baseSpecialDefense = 80,
            baseSpeed = 45,
        )

    val TORKOAL: Species =
        Species(
            name = "Torkoal",
            types = listOf(Type.FIRE),
            baseHp = 70,
            baseAttack = 85,
            baseDefense = 140,
            baseSpecialAttack = 85,
            baseSpecialDefense = 70,
            baseSpeed = 20,
        )

    val TORNADUS_INCARNATE: Species =
        Species(
            name = "Tornadus Incarnate",
            types = listOf(Type.FLYING),
            baseHp = 79,
            baseAttack = 115,
            baseDefense = 70,
            baseSpecialAttack = 125,
            baseSpecialDefense = 80,
            baseSpeed = 111,
        )

    val TORNADUS_THERIAN: Species =
        Species(
            name = "Tornadus Therian",
            types = listOf(Type.FLYING),
            baseHp = 79,
            baseAttack = 100,
            baseDefense = 80,
            baseSpecialAttack = 110,
            baseSpecialDefense = 90,
            baseSpeed = 121,
        )

    val TOXAPEX: Species =
        Species(
            name = "Toxapex",
            types = listOf(Type.POISON, Type.WATER),
            baseHp = 50,
            baseAttack = 63,
            baseDefense = 152,
            baseSpecialAttack = 53,
            baseSpecialDefense = 142,
            baseSpeed = 35,
        )

    val TYRANITAR: Species =
        Species(
            name = "Tyranitar",
            types = listOf(Type.ROCK, Type.DARK),
            baseHp = 100,
            baseAttack = 134,
            baseDefense = 110,
            baseSpecialAttack = 95,
            baseSpecialDefense = 100,
            baseSpeed = 61,
        )

    val URSALUNA: Species =
        Species(
            name = "Ursaluna",
            types = listOf(Type.GROUND, Type.NORMAL),
            baseHp = 130,
            baseAttack = 140,
            baseDefense = 105,
            baseSpecialAttack = 45,
            baseSpecialDefense = 80,
            baseSpeed = 50,
        )

    val URSALUNA_BLOODMOON: Species =
        Species(
            name = "Ursaluna Bloodmoon",
            types = listOf(Type.GROUND, Type.NORMAL),
            baseHp = 113,
            baseAttack = 70,
            baseDefense = 120,
            baseSpecialAttack = 135,
            baseSpecialDefense = 65,
            baseSpeed = 52,
        )

    val URSHIFU_RAPID_STRIKE: Species =
        Species(
            name = "Urshifu Rapid Strike",
            types = listOf(Type.FIGHTING, Type.WATER),
            baseHp = 100,
            baseAttack = 130,
            baseDefense = 100,
            baseSpecialAttack = 63,
            baseSpecialDefense = 60,
            baseSpeed = 97,
        )

    val URSHIFU_SINGLE_STRIKE: Species =
        Species(
            name = "Urshifu Single Strike",
            types = listOf(Type.FIGHTING, Type.DARK),
            baseHp = 100,
            baseAttack = 130,
            baseDefense = 100,
            baseSpecialAttack = 63,
            baseSpecialDefense = 60,
            baseSpeed = 97,
        )

    val VENUSAUR: Species =
        Species(
            name = "Venusaur",
            types = listOf(Type.GRASS, Type.POISON),
            baseHp = 80,
            baseAttack = 82,
            baseDefense = 83,
            baseSpecialAttack = 100,
            baseSpecialDefense = 100,
            baseSpeed = 80,
        )

    val VOLCARONA: Species =
        Species(
            name = "Volcarona",
            types = listOf(Type.BUG, Type.FIRE),
            baseHp = 85,
            baseAttack = 60,
            baseDefense = 65,
            baseSpecialAttack = 135,
            baseSpecialDefense = 105,
            baseSpeed = 100,
        )

    val WALKING_WAKE: Species =
        Species(
            name = "Walking Wake",
            types = listOf(Type.WATER, Type.DRAGON),
            baseHp = 99,
            baseAttack = 83,
            baseDefense = 91,
            baseSpecialAttack = 125,
            baseSpecialDefense = 83,
            baseSpeed = 109,
        )

    val WEAVILE: Species =
        Species(
            name = "Weavile",
            types = listOf(Type.DARK, Type.ICE),
            baseHp = 70,
            baseAttack = 120,
            baseDefense = 65,
            baseSpecialAttack = 45,
            baseSpecialDefense = 85,
            baseSpeed = 125,
        )

    val WHIMSICOTT: Species =
        Species(
            name = "Whimsicott",
            types = listOf(Type.GRASS, Type.FAIRY),
            baseHp = 60,
            baseAttack = 67,
            baseDefense = 85,
            baseSpecialAttack = 77,
            baseSpecialDefense = 75,
            baseSpeed = 116,
        )

    val ZAMAZENTA: Species =
        Species(
            name = "Zamazenta",
            types = listOf(Type.FIGHTING),
            baseHp = 92,
            baseAttack = 120,
            baseDefense = 115,
            baseSpecialAttack = 80,
            baseSpecialDefense = 115,
            baseSpeed = 138,
        )

    val ZAPDOS: Species =
        Species(
            name = "Zapdos",
            types = listOf(Type.ELECTRIC, Type.FLYING),
            baseHp = 90,
            baseAttack = 90,
            baseDefense = 85,
            baseSpecialAttack = 125,
            baseSpecialDefense = 90,
            baseSpeed = 100,
        )

    /** All generated species, keyed by display name. */
    val all: Map<String, Species> =
        mapOf(
            "Alakazam" to ALAKAZAM,
            "Alomomola" to ALOMOMOLA,
            "Amoonguss" to AMOONGUSS,
            "Arcanine Hisui" to ARCANINE_HISUI,
            "Archaludon" to ARCHALUDON,
            "Blacephalon" to BLACEPHALON,
            "Blastoise" to BLASTOISE,
            "Blaziken" to BLAZIKEN,
            "Blissey" to BLISSEY,
            "Breloom" to BRELOOM,
            "Ceruledge" to CERULEDGE,
            "Charizard" to CHARIZARD,
            "Chi Yu" to CHI_YU,
            "Chien Pao" to CHIEN_PAO,
            "Cinderace" to CINDERACE,
            "Clefable" to CLEFABLE,
            "Conkeldurr" to CONKELDURR,
            "Corviknight" to CORVIKNIGHT,
            "Crawdaunt" to CRAWDAUNT,
            "Darkrai" to DARKRAI,
            "Dondozo" to DONDOZO,
            "Dragapult" to DRAGAPULT,
            "Dragonite" to DRAGONITE,
            "Excadrill" to EXCADRILL,
            "Farigiraf" to FARIGIRAF,
            "Ferrothorn" to FERROTHORN,
            "Flutter Mane" to FLUTTER_MANE,
            "Forretress" to FORRETRESS,
            "Garchomp" to GARCHOMP,
            "Garganacl" to GARGANACL,
            "Gengar" to GENGAR,
            "Gholdengo" to GHOLDENGO,
            "Glimmora" to GLIMMORA,
            "Gliscor" to GLISCOR,
            "Great Tusk" to GREAT_TUSK,
            "Hatterene" to HATTERENE,
            "Heatran" to HEATRAN,
            "Incineroar" to INCINEROAR,
            "Indeedee Female" to INDEEDEE_FEMALE,
            "Iron Crown" to IRON_CROWN,
            "Iron Moth" to IRON_MOTH,
            "Iron Treads" to IRON_TREADS,
            "Iron Valiant" to IRON_VALIANT,
            "Jellicent Male" to JELLICENT_MALE,
            "Jirachi" to JIRACHI,
            "Kartana" to KARTANA,
            "Keldeo Ordinary" to KELDEO_ORDINARY,
            "Kingambit" to KINGAMBIT,
            "Kyurem" to KYUREM,
            "Kyurem Black" to KYUREM_BLACK,
            "Landorus Incarnate" to LANDORUS_INCARNATE,
            "Landorus Therian" to LANDORUS_THERIAN,
            "Latios" to LATIOS,
            "Magnezone" to MAGNEZONE,
            "Melmetal" to MELMETAL,
            "Mew" to MEW,
            "Ninetales" to NINETALES,
            "Ninetales Alola" to NINETALES_ALOLA,
            "Ogerpon Hearthflame Mask" to OGERPON_HEARTHFLAME_MASK,
            "Ogerpon Wellspring Mask" to OGERPON_WELLSPRING_MASK,
            "Pecharunt" to PECHARUNT,
            "Pelipper" to PELIPPER,
            "Pikachu" to PIKACHU,
            "Politoed" to POLITOED,
            "Raging Bolt" to RAGING_BOLT,
            "Regidrago" to REGIDRAGO,
            "Reuniclus" to REUNICLUS,
            "Rillaboom" to RILLABOOM,
            "Rotom Wash" to ROTOM_WASH,
            "Samurott Hisui" to SAMUROTT_HISUI,
            "Scizor" to SCIZOR,
            "Skarmory" to SKARMORY,
            "Slowbro" to SLOWBRO,
            "Slowking Galar" to SLOWKING_GALAR,
            "Starmie" to STARMIE,
            "Tapu Fini" to TAPU_FINI,
            "Tapu Koko" to TAPU_KOKO,
            "Tapu Lele" to TAPU_LELE,
            "Tatsugiri Curly" to TATSUGIRI_CURLY,
            "Tentacruel" to TENTACRUEL,
            "Thundurus Therian" to THUNDURUS_THERIAN,
            "Ting Lu" to TING_LU,
            "Torkoal" to TORKOAL,
            "Tornadus Incarnate" to TORNADUS_INCARNATE,
            "Tornadus Therian" to TORNADUS_THERIAN,
            "Toxapex" to TOXAPEX,
            "Tyranitar" to TYRANITAR,
            "Ursaluna" to URSALUNA,
            "Ursaluna Bloodmoon" to URSALUNA_BLOODMOON,
            "Urshifu Rapid Strike" to URSHIFU_RAPID_STRIKE,
            "Urshifu Single Strike" to URSHIFU_SINGLE_STRIKE,
            "Venusaur" to VENUSAUR,
            "Volcarona" to VOLCARONA,
            "Walking Wake" to WALKING_WAKE,
            "Weavile" to WEAVILE,
            "Whimsicott" to WHIMSICOTT,
            "Zamazenta" to ZAMAZENTA,
            "Zapdos" to ZAPDOS,
        )
}
