package com.pokemon.battle.ingest.codegen

import com.pokemon.battle.data.SpeciesJson
import kotlinx.serialization.json.Json
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.readText

private val SPECIES_DIR: Path = Path.of("engine/src/main/resources/pokedex/species")
private val MANIFEST: Path = SPECIES_DIR.resolve("index.txt")
private val OUTPUT: Path = Path.of("engine/src/main/kotlin/com/pokemon/battle/data/PokedexCatalog.kt")

/**
 * Reads the JSON species the ingestion pipeline produced and emits a generated
 * Kotlin catalog: `object PokedexCatalog { val PIKACHU = Species(...); ... }`.
 *
 * Diary 064. Sister to [com.pokemon.battle.data.Pokedex.loadJsonFromClasspath]:
 * same source data, two consumption shapes (string-keyed map vs symbol fields).
 * The generated file gets a "do not edit" header — re-running this command is
 * the canonical way to update it.
 */
fun main() {
    require(Files.exists(MANIFEST)) { "Run :data-ingestion:run first to populate $MANIFEST" }
    val json = Json { ignoreUnknownKeys = true }

    val slugs =
        MANIFEST.readText().lines()
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("#") }
            .sorted()

    val entries =
        slugs.map { slug ->
            val species = json.decodeFromString(SpeciesJson.serializer(), SPECIES_DIR.resolve("$slug.json").readText())
            slug.toValName() to species
        }

    val src =
        buildString {
            append(
                """
                // Generated by :data-ingestion:codegenSpecies — do not edit.
                // Source of truth: engine/src/main/resources/pokedex/species/<slug>.json (diary 064).
                // Re-run `./gradlew :data-ingestion:codegenSpecies` to regenerate after re-ingestion.
                package com.pokemon.battle.data

                import com.pokemon.battle.model.Species
                import com.pokemon.battle.model.Type

                /**
                 * Generated species catalog. Symbol-keyed counterpart to
                 * [Pokedex.loadJsonFromClasspath]; both produce the same domain values.
                 * Pick whichever consumption shape suits the call site (see diary 064).
                 */
                @Suppress("LargeClass", "ObjectPropertyNaming") // Generated; one val per species.
                object PokedexCatalog {

                """.trimIndent(),
            )
            for ((valName, species) in entries) {
                append("    val ").append(valName).append(": Species = Species(\n")
                append("        name = ").append(quote(species.name)).append(",\n")
                append("        types = listOf(").append(species.types.joinToString { "Type.$it" }).append("),\n")
                append("        baseHp = ").append(species.baseHp).append(",\n")
                append("        baseAttack = ").append(species.baseAttack).append(",\n")
                append("        baseDefense = ").append(species.baseDefense).append(",\n")
                append("        baseSpecialAttack = ").append(species.baseSpecialAttack).append(",\n")
                append("        baseSpecialDefense = ").append(species.baseSpecialDefense).append(",\n")
                append("        baseSpeed = ").append(species.baseSpeed).append(",\n")
                append("    )\n\n")
            }
            // Convenience map for callers that still want a name-keyed lookup.
            append("    /** All generated species, keyed by display name. */\n")
            append("    val all: Map<String, Species> = mapOf(\n")
            for ((valName, species) in entries) {
                append("        ").append(quote(species.name)).append(" to ").append(valName).append(",\n")
            }
            append("    )\n")
            append("}\n")
        }

    Files.writeString(OUTPUT, src)
    println("Wrote $OUTPUT (${entries.size} species)")
}

/** PokeAPI slug to UPPER_SNAKE val name. `great-tusk` becomes `GREAT_TUSK`. */
private fun String.toValName(): String = uppercase().replace('-', '_')

private fun quote(s: String): String = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
