package com.pokemon.battle.ingest.cli

import com.pokemon.battle.ingest.fetch.PokeApiClient
import com.pokemon.battle.ingest.transform.PokeApiAbility
import com.pokemon.battle.ingest.transform.PokeApiItem
import com.pokemon.battle.ingest.transform.englishShort
import com.pokemon.battle.model.Ability
import com.pokemon.battle.model.Item
import kotlinx.serialization.json.Json
import java.nio.file.Path

/**
 * Audits the gap between PokeAPI's representation of items / abilities and our
 * internal `enum class` model. For each value in our `Item` and `Ability` enums,
 * fetches the corresponding PokeAPI record and prints what PokeAPI knows that we
 * don't (category, attributes, generation, fling power, effect text).
 *
 * Output is a markdown table to stdout — copy into a diary or PR description
 * when motivating an enum-to-data-class refactor (see diary 064's update).
 */
fun main() {
    val client = PokeApiClient(cacheRoot = Path.of(".cache/pokeapi"))
    val json = Json { ignoreUnknownKeys = true }

    println("# Model gap audit: PokeAPI vs our enums")
    println()
    println("Generated by `:data-ingestion:auditModelGap`. Diary 064.")
    println()
    auditItems(client, json)
    println()
    auditAbilities(client, json)
}

private fun auditItems(
    client: PokeApiClient,
    json: Json,
) {
    println("## Items (${Item.entries.size} in our enum)")
    println()
    println("| Our enum | PokeAPI category | Attributes | Fling power | Effect (short) |")
    println("|---|---|---|---|---|")
    for (item in Item.entries) {
        val slug = item.name.lowercase().replace('_', '-')
        val raw = client.fetch("item", slug)
        val dto = json.decodeFromString(PokeApiItem.serializer(), raw)
        val attrs = dto.attributes.joinToString(", ") { it.name }
        val effect = dto.effectEntries.englishShort().take(80)
        println("| `${item.name}` | ${dto.category.name} | $attrs | ${dto.flingPower ?: "—"} | $effect |")
    }
}

private fun auditAbilities(
    client: PokeApiClient,
    json: Json,
) {
    println("## Abilities (${Ability.entries.size} in our enum)")
    println()
    println("| Our enum | Generation | Effect (short) |")
    println("|---|---|---|")
    for (ability in Ability.entries) {
        val slug = ability.name.lowercase().replace('_', '-')
        val raw =
            try {
                client.fetch("ability", slug)
            } catch (_: PokeApiClient.FetchException) {
                println("| `${ability.name}` | — (slug $slug 404) | — |")
                continue
            }
        val dto = json.decodeFromString(PokeApiAbility.serializer(), raw)
        val effect = dto.effectEntries.englishShort().take(100)
        println("| `${ability.name}` | ${dto.generation.name} | $effect |")
    }
}
